exports.queryList = {
  GET_STORE_LIST_QUERY : 'SELECT ID, STORE_NAME, STORE_CODE FROM BOOK_STORE.STORES' , 
   
  SAVE_STORE_QUERY : 'INSERT INTO BOOK_STORE.STORES (STORE_NAME, STORE_CODE, ADDRESS , CREATED_BY , CREATED_ON) VALUES($1, $2, $3, $4, $5)',

  GET_BOOK_LIST_QUERY : 'SELECT ID, TITLE, AUTHOR, PUBLISHER FROM BOOK_STORE.BOOKS',
   
  GET_BOOK_DETAILS_QUERY : `SELECT ID, TITLE, DESCRIPTION, AUTHOR, PUBLISHER, PAGES
                            , BOOKS.STORE_CODE, stores.store_name , store.address  FROM BOOK_STORE.BOOKS INNER JOIN  BOOK_STORE.STORES ON BOOKS.STORE_CODE  = STORES.STORE_CODE 
                            WHERE ID =$1`,
    
  SAVE_BOOK_QUERY : ` INSERT INTO BOOK_STORE.BOOKS (TITLE, ISBN,DESCRIPTION, AUTHOR, PUBLISHER, PAGES, STORE_CODE, CREATED_BY , CREATED_ON)
                        VALUES($1, $2, $3, $4, $5 , $6 , $7 , $8,$9) `,

  UPDATE_BOOK_QUERY : `
                    UPDATE BOOK_STORE.BOOKS SET TITLE=$1, DESCRIPTION=$2, AUTHOR=$3, PUBLISHER=$4, 
                    PAGES=$5, STORE_CODE=$6, CREATED_BY=$7 , CREATED_ON=$8
                    WHERE ID=$9
    `,

    DELETE_BOOK_QUERY : ` DELETE FROM BOOK_STORE.BOOKS WHERE ID=$1 `,
}