exports.queryList = {
  GET_STORE_LIST_QUERY : 'SELECT ID, STORE_NAME, STORE_CODE FROM BOOK_STORE.STORES' , 
   
  SAVE_STORE_QUERY : 'INSERT INTO BOOK_STORE.STORES (STORE_NAME, STORE_CODE, ADDRESS , CREATED_BY , CREATED_ON) VALUES($1, $2, $3, $4, $5)',
}